services:
  api:
    build:
      context: .
      dockerfile: ./BuildYourHead.Api/Dockerfile
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=server=${DB_HOST};port=${DB_PORT};database=BuildYourHead;user=root;password=superadmin;

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'build-your-head'
      MYSQL_ROOT_PASSWORD: 'superadmin'
    ports:
      - '3306:3306'
    expose:
      - '3306'