version: "3.3"

services:
  api:
    build:
      context: ./src
      dockerfile: ./Shynest.Identity.Server/Dockerfile
    container_name: identity-server
    ports:
      - "7264:7264"
    environment:
      - Application__PathBase=/auth
      - ConnectionStrings__Identity=server=mysql;port=3306;database=Identity;user=root;password=shynest_db_pass;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7264
    networks:
      - shynest-apps

networks:
  shynest-apps:
    external: true