version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: ./src/Shynest.Identity.Server/Dockerfile
    container_name: identity-server
    ports:
      - "7264:7264"
    environment:
      - PathBase=/auth
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7264