version: "3.3"

services:
  ui:
    build: ./build-your-head-ui/
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${API_URL}
      - REACT_APP_OIDC_URL=${}